#!/usr/bin/sh

# note to self: this is a bash script, launch everything you want to launch at runtime here

sxhkd &

polybar -r example &

picom &

feh --bg-center ~/Pictures/bg.png &

bspc monitor LVDS-1 -d 1 2 3 4 5 6

xrandr --output LVDS-1 --primary --mode 1366x768 --rate 60

# todo configure border colors to something i can eventually agree on alongside my polybar config

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# note: ^8 means window spawns on workspace 8

#second monitor setup
bspc rule -a Discord desktop='^9' focus=on
bspc rule -a deadbeef desktop='^9' focus=on
#i browse a lot so firefox time
bspc rule -a firefox desktop='^1'
